### ISSUE TITLE
Making Home page Responsive

### ISSUE THREAD

**Issue by Atif0604** [arpit456jain/CodingEasy#1]
Want to make home page responsive
Assign me under SWOC'21
@arpit456jain

**Comment by arpit456jain** [comment]
go ahead @Atif0604

**Comment by ssurbhi09** [comment]
What type of homepage?

**Comment by arpit456jain** [comment]
@ssurbhi09 r u swoc'21 participant

**Comment by ssurbhi09** [comment]
Yes @arpit456jain

**Comment by arpit456jain** [comment]
I am creating new issues work on that
