### ISSUE TITLE
Bug in contact us feature

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#113]

**Comment by arpit456jain** [comment]
@prateekmohanty63 can u do this ?

**Comment by prateekmohanty63** [comment]
Yes sure Assign me 
I will do it
@arpit456jain

**Comment by arpit456jain** [comment]
actually there is no models for contact us so do this.
1.move urls (only contact us for now) from Codingeasy project app to home app because we can't create models there
![image](https://user-images.githubusercontent.com/55352601/151770989-93590606-cfd0-4234-b2b5-eba53e61133f.png)

**Comment by arpit456jain** [comment]
And move its code from codingeasy.views to home.views
![image](https://user-images.githubusercontent.com/55352601/151771150-ca6db203-0cb4-4ce5-8906-0139587acb7f.png)

**Comment by arpit456jain** [comment]
i hope you got it @prateekmohanty63

**Comment by prateekmohanty63** [comment]
@arpit456jain done

**Comment by prateekmohanty63** [comment]
@arpit456jain  should I use that code which you have shown in the picture?

**Comment by arpit456jain** [comment]
its on u @prateekmohanty63 i just want the contact us faeture to be implemented the previous contributor has used that code

**Comment by prateekmohanty63** [comment]
ok got it , i will try doing it asap

**Comment by prateekmohanty63** [comment]
@arpit456jain I have written the code for contact 
Sending a mail to coding easy

**Comment by prateekmohanty63** [comment]
But the fact is that I am unable to test is because due to some reason the front end is not sending the post request to the desired route

**Comment by prateekmohanty63** [comment]
But the code which I have used works perfectly fine
cause i have used it in my own project to send mails

**Comment by arpit456jain** [comment]
@Snehaa1203 can you please help him

**Comment by prateekmohanty63** [comment]
![image](https://user-images.githubusercontent.com/72243320/152020455-1b95b4df-d125-47ac-8b7b-6eb6bb62b34f.png)
This is the code @arpit456jain

**Comment by prateekmohanty63** [comment]
@arpit456jain  I have fixed the code
and also checked it using postman for the email sending

**Comment by prateekmohanty63** [comment]
In the setting.py I have my email credentials
Hence I am removing them 
Add your own credentials and it would work fine

**Comment by prateekmohanty63** [comment]
![image](https://user-images.githubusercontent.com/72243320/152639307-f926e4cc-4527-4d1d-a0b5-6924900a35e5.png)

Here is the postman screenshort

**Comment by arpit456jain** [comment]
Ok @prateekmohanty63 great 👍

**Comment by prateekmohanty63** [comment]
@arpit456jain  I just removed the space can you check it

**Comment by prateekmohanty63** [comment]
Ok @arpit456jain I will fetch from upstream and send the pr by today

**Comment by arpit456jain** [comment]
Sure @prateekmohanty63 
Don't worry u will get a hard label

**Comment by prateekmohanty63** [comment]
@arpit456jain I have resolved all the conflicts 
Please review the code and merge it

**Comment by prateekmohanty63** [comment]
@arpit456jain  I have a doubt can you explain me one thing
Like how will these contributions be counted for my SWOC profile
Like is it linked or something 

It is my first time so I am not sure :)

**Comment by arpit456jain** [comment]
@prateekmohanty63 u have to comment your partipant on Google sheets of project id 11 after that i can update your points there.

**Comment by prateekmohanty63** [comment]
oh wow thanks 
@arpit456jain if there are anymore stuff that I can do 
Please do let me know

And thanks for all your support

**Comment by prateekmohanty63** [comment]
@arpit456jain 

![image](https://user-images.githubusercontent.com/72243320/152653041-226d61cc-4a72-4ae2-8d9c-24ec4ec8d442.png)

It is showing locked , how should i Enter my pr number there?

**Comment by prateekmohanty63** [comment]
![image](https://user-images.githubusercontent.com/72243320/152654074-10b96e2c-b4cc-4e53-8a3c-af72406311fe.png)

@arpit456jain  Like they have written these numbers I am confused what are these numbers
And what should I write?

**Comment by arpit456jain** [comment]
@prateekmohanty63 u can contact to any participant they can tell you better than me

**Comment by codervivek5** [comment]
I can remove this bug in contact us page plz assign it me.

**Comment by arpit456jain** [comment]
@codervivek5 go ahead 
implement 2 things
1. the query should send to my mail 
2. save it in database
