### ISSUE TITLE
Styling is needed in the UI.

### ISSUE THREAD

**Issue by AGENT-SRINJOY** [arpit456jain/CodingEasy#126]
styling is needed in  the navigation bar , fonts and some more .

**Comment by CoderSahil128** [comment]
> styling is needed in the navigation bar , fonts and some mohi

> styling is needed in the navigation bar , fonts and some more .

Hi there. I'm a GSSOC 2022 contributor. I've done a few projects regarding front-end, previously. So I can do this project in a better way .Plz assign this project to me.

**Comment by arpit456jain** [comment]
@srinjoy-26 first come first serve .
if he is unable to do it i will assign it to you

**Comment by Aditya3403** [comment]
Sir, I would like to work on this issue. Kindly assign this issue to me.

**Comment by arpit456jain** [comment]
@AGENT-SRINJOY make PR

**Comment by arpit456jain** [comment]
> > styling is needed in the navigation bar , fonts and some mohi
> 
> > styling is needed in the navigation bar , fonts and some more .
> 
> Hi there. I'm a GSSOC 2022 contributor. I've done a few projects regarding front-end, previously. So I can do this project in a better way .Plz assign this project to me.

go ahead @CoderSahil128 make PR within 2 days
