### ISSUE TITLE
want to add best features

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [arpit456jain/CodingEasy#127]
hello @arpit i really want to work on this project so can you please assign me. i am gssoc contributor.

**Comment by Khushbu-kumari-87090** [comment]
i  have familiar with  html,css and java script so i add to create some awesome fonts and add  to some cool webpages under your guidance. so please assign me.

**Comment by Khushbu-kumari-87090** [comment]
and thanks for reply.

**Comment by Khushbu-kumari-87090** [comment]
and i have familiar with java so also code the project so  please assign me @Arpit.

**Comment by arpit456jain** [comment]
@Khushbu-kumari-87090 please contact to mentors in our channel tag them and describe the feature u want to add they will assign u
