### ISSUE TITLE
add hot topics list in navbar

### ISSUE THREAD

**Issue by Akash-Singh-007** [arpit456jain/CodingEasy#130]
Adding a list of top 3-5 cources in the navbar for easy search.

**Comment by arpit456jain** [comment]
@Akash-Singh-007 can u implement search feature ?

**Comment by Akash-Singh-007** [comment]
I will add a list of topics, so anyone can directly reach there instead of scrolling the whole page.

**Comment by Akash-Singh-007** [comment]
> @Akash-Singh-007 can u implement search feature ?
I have made a similar project like this.

http://omnix.epizy.com/?i=1

You can check the menu bar

**Comment by aayushray** [comment]
I can implement navbar, that will be having the options to search a topic,  and it will contains the courses list, described within the heading. For example, **Programming language** will contain topics like C++, Java, Javascript **Web Development** part  will contain HTML, CSS, Bootstrap course, and similarly, Machine learning course will be a separate one.

**Comment by arpit456jain** [comment]
> I will add a list of topics, so anyone can directly reach there instead of scrolling the whole page.

its not needed

**Comment by arpit456jain** [comment]
> I can implement navbar, that will be having the options to search a topic, and it will contains the courses list, described within the heading. For example, **Programming language** will contain topics like C++, Java, Javascript **Web Development** part will contain HTML, CSS, Bootstrap course, and similarly, Machine learning course will be a separate one. Further, the navbar will have options to Contact and to Login/ Logout.

@aayushray create a issue for that
