### ISSUE TITLE
[DOCUMENTATION] Readme file enhancement.

### ISSUE THREAD

**Issue by Susmita-Dey** [arpit456jain/CodingEasy#131]
I want to enhance the README.md file of this repo.
I'm a GSSOC'22 contributor and I can work on this issue.
Kindly assign it to me.

**Comment by Avik-creator** [comment]
I would like to take this issue. If it is up for grabs I would like to take it

**Comment by arpit456jain** [comment]
go ahead @Susmita-Dey

**Comment by Susmita-Dey** [comment]
Thanks for assigning it to me.
**Kindly give this issue and my upcoming PR labelled as GSSOC22 so that mentors can count my contribution.**
