### ISSUE TITLE
AttributeError: module 'CodingEasy.views' has no attribute 'contact'

### ISSUE THREAD

**Issue by Aman16-ai** [arpit456jain/CodingEasy#133]

**Comment by Aman16-ai** [comment]
please assigne this issue to me

**Comment by aayushray** [comment]
Can solve this issue, as there are few mistakes in the code, that has to be rectified.

**Comment by HarshKumarChoudary** [comment]
Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant
