### ISSUE TITLE
Sign in and Sign up of the website not working

### ISSUE THREAD

**Issue by kiran11621** [arpit456jain/CodingEasy#137]
I would love to work on sign in and sign up part of the project.

**Comment by kiran11621** [comment]
Welcome, so is this issue assigned to me?

**Comment by Aditya3403** [comment]
I would like to work on this issue. Kindly assign this issue to me.

**Comment by arpit456jain** [comment]
@kiran11621 i hop u can implement the login and signup part

**Comment by kiran11621** [comment]
Yes, Arpit Jain I can. Please do assign me.

**Comment by Aman16-ai** [comment]
can u please assign me this issue

**Comment by HarshKumarChoudary** [comment]
Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant

**Comment by rajat4885** [comment]
I would like to work on this issue, can you please assign me? I am a GSSOC'22 participant.
Kindly assign me this issue.
