### ISSUE TITLE
Work on UI of the Webpages

### ISSUE THREAD

**Issue by kiran11621** [arpit456jain/CodingEasy#138]
I would like to improve the UI of the home page. I will add attractive cards and an appropriate carousel to make it look good and user-friendly.

So, please do assign me this issue.
#gssoc

**Comment by arpit456jain** [comment]
@kiran11621 u can start work now please make PR asap

**Comment by kiran11621** [comment]
Yes I will make today

**Comment by arpit456jain** [comment]
@kiran11621 make PR asap for issue #204
