### ISSUE TITLE
[ENHANCEMENTS] Create a Proper Folder Architecture, a "Blogs" Section and Improving Authentication System.

### ISSUE THREAD

**Issue by ephemeralshay** [arpit456jain/CodingEasy#139]
**1. Create a Blogs Section -**
(a) Present users with insightful (concise yet powerful) blogs, which talk about various tech domains.
(b) Allow users to create, read, update and delete blog. Users other than author cannot delete the blogs.
(c) Authors can have their profile pics on the blog preview card. Clicking on it leads to their Profile on the website.

**2. Improve Authentication System and Contact Us Section -** 
(a) Use “Crispy forms” for user registration instead of the current authentication layout. Crispy Forms uses bootstrap as default styling engine, which will lead to more uniformity in the website (as opposed to the current case; login/signup and contact us pages are quite buggy). 
(b) Same applies for the Contact Us section.

I have the required experience for incorporating above stated enhancements. Could you please assign this task to me? 
Thank you.

**Comment by arpit456jain** [comment]
@ephemeralshay in this PR just work on blog system for admin only

**Comment by arpit456jain** [comment]
@ephemeralshay

**Comment by ephemeralshay** [comment]
I'll first work on authentication system @arpit456jain

**Comment by arpit456jain** [comment]
Ok @ephemeralshay but make sure you only work on authentication no other feature

**Comment by arpit456jain** [comment]
@ephemeralshay implement the blog section asap

**Comment by ephemeralshay** [comment]
Okay

**Comment by arpit456jain** [comment]
@ephemeralshay any updates ?

**Comment by ephemeralshay** [comment]
Yes, working on it. I will create a PR in a day or two.

**Comment by ephemeralshay** [comment]
Yes, working on it. I will create a PR in a day or two.

**Comment by ephemeralshay** [comment]
Yes, working on it. I will create a PR in a day or two.
