### ISSUE TITLE
Logo redirect correction

### ISSUE THREAD

**Issue by prateekmohanty63** [arpit456jain/CodingEasy#147]
The left logo of coding easy on clicking doesn't redirect the user to index.html
Instead its giving an error

I want to fix this issue, can you please assign me this under GSSOC22

**Comment by prateekmohanty63** [comment]
@arpit456jain

**Comment by prateekmohanty63** [comment]
@arpit456jain  can you assign me this task?

**Comment by prateekmohanty63** [comment]
![image](https://user-images.githubusercontent.com/72243320/156982237-e1205cd6-569e-4115-9cfd-3ccb99212b35.png)

**Comment by arpit456jain** [comment]
ok @prateekmohanty63

**Comment by prateekmohanty63** [comment]
@arpit456jain  I have created the PR for this issue
Please review the PR and merge it
Thank you
