### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by sripor62** [arpit456jain/CodingEasy#148]
I want to improve the dashboard and make it more attractive as it has an HttpResponse of  hello dashboard now

**Comment by bhavyapathak20** [comment]
@saketsagarsingh 
I would like to work on this issue.
My Skills in web development :

1)HTML
2)CSS
3)Bootstrap
4)Javascript
5)Jquery

My experience :
5+ months of experience in UI design.
Worked on Hands-on projects. My Github repo shows it

**Comment by sripor62** [comment]
> /assign



> /assign

hey.Actually I am new to open source ...I am not getting exactly why you have commented this
