### ISSUE TITLE
Page Not found 

### ISSUE THREAD

**Issue by Tusharjagi** [arpit456jain/CodingEasy#152]
## Description 
- When we click on  _Coding Easy_  in Nav section it show  ***Page Not Found***

> - Can I fix this , Please assign me under a GSSOC22
> - I'm a participant of `GSSOC22`

### Screenshots

![screencapture-127-0-0-1-8000-index-html-2022-03-05-15_30_16](https://user-images.githubusercontent.com/12596457/156878689-4372260b-02e6-424b-a875-84ce26deb350.png)

**Comment by arpit456jain** [comment]
@Tusharjagi check again
if still there is any page which is missing do let me know

**Comment by Tusharjagi** [comment]
@arpit456jain Same Issue 
- That issue not solved.
- Continue Shows Page Not found (404)

**Comment by KKhushhalR2405** [comment]
> 

Hi @Tusharjagi, This issue has been solved a few days back. Are you sure you are using the updated version of the code? Try pulling the latest code and see if the problem still persists. Thank You
