### ISSUE TITLE
Updating feature.html

### ISSUE THREAD

**Issue by sripor62** [arpit456jain/CodingEasy#169]
### Description

The feature.html file can be updated as presented in the screenshot

### Screenshots

![Screenshot (215)](https://user-images.githubusercontent.com/94283961/157237640-9202ba21-36b9-4c35-8783-09f794fe68d4.png)

**Comment by rishav-karanjit** [comment]
Can I get assigned to this issue?

**Comment by KKhushhalR2405** [comment]
Assigning you the same @sripor62

**Comment by sripor62** [comment]
@KKhushhalR2405  I have worked on the code .Now what should I do?Can you plz help
