### ISSUE TITLE
Adding a new course

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#170]
### Description

if u want to add a new course **create a new issue** for that and explain it in brief 

**Do not comment under this issue** for assign this is a general issue 
Do not spam in its comment section.

example for New courses which can be added
1.React
2.django
3.Java
4.STL

and so on

**Comment by saketsagarsingh** [comment]
@arpit456jain I want to work on this issue, please assign to me for gssoc'22

**Comment by arpit456jain** [comment]
> ### Description
> if u want to add a new course **create a new issue** for that and explain it in brief
> 
> **Do not comment under this issue** for assign this is a general issue Do not spam in its comment section.
> 
> example for New courses which can be added 1.React 2.django 3.Java 4.STL
> 
> and so on
> 
> ### Screenshots
> _No response_

@saketsagarsingh read this properly
