### ISSUE TITLE
Updating Navbar

### ISSUE THREAD

**Issue by aayushray** [arpit456jain/CodingEasy#171]
### Description

Implementation of navbar, that will be having the options to search a topic, and it will contains the courses list, described within the heading. For example, Programming language will contain topics like C++, Java, Javascript Web Development part will contain HTML, CSS, Bootstrap course, and similarly, Machine learning course will be a separate one. Further, the navbar will have options to Contact and to Login/ Logout.

**Comment by KKhushhalR2405** [comment]
Hi @aayushray, that's a nice feature. Having a search bar can really help the user to browse all the available courses. You can start working on it.

**Comment by aayushray** [comment]
Sure, will start the work soon. Thank You for assigning the task.

**Comment by KKhushhalR2405** [comment]
Hi @aayushray, Can you share your progress. You can always ask for help if you need it and try to make a PR as soon as possible.

**Comment by meghagangadhar13** [comment]
Can I work on this issue under GSSOC 22

**Comment by arpit456jain** [comment]
@meghagangadhar13 if he didn't respond in w days it will be assigned to you

**Comment by aayushray** [comment]
Will resolve this issue by this weekend.
