### ISSUE TITLE
Adding Django Course 

### ISSUE THREAD

**Issue by SheetalChouhan12** [arpit456jain/CodingEasy#172]
### Description

I want to add Django course in the courses section of the website

**Comment by Muhammad-Galhoum** [comment]
Hello @SheetalChouhan12  , I hope you fine 
Can you please assign this issue to me

**Comment by SheetalChouhan12** [comment]
> Hello @SheetalChouhan12 , I hope you fine Can you please assign this issue to me

Hey I think you misunderstood , I'm already working on this issue .I just added this issue separately as @arpit456jain said

**Comment by KKhushhalR2405** [comment]
Hi @SheetalChouhan12. We are working on making a template so that you can use it to add courses. We will update you when we are done. In meantime, you can start preparing the content and as soon as we provide the template, you can use it and make a Pull Request. Thank You

**Comment by KKhushhalR2405** [comment]
The templates are provided [here](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/SampleCourse) along with the instructions. If you are not familiar with Django, you can leave the URL mapping part and mention it in the PR, so someone else will do it. If you are familiar with Django, you can try mapping the URLs on your own. You can always ask for help on our discord channel. Assigning you the same.

**Comment by SheetalChouhan12** [comment]
> The templates are provided [here](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/SampleCourse) along with the instructions. If you are not familiar with Django, you can leave the URL mapping part and mention it in the PR, so someone else will do it. If you are familiar with Django, you can try mapping the URLs on your own. You can always ask for help on our discord channel. Assigning you the same.

Okay and Yes I know About Django

**Comment by SheetalChouhan12** [comment]
@arpit456jain @KKhushhalR2405  I'm new to GitHub , by mistake click on "unassigned " will someone assign me this issue again

**Comment by SheetalChouhan12** [comment]
> @SheetalChouhan12 What's the status of your work?

Its 90% done

**Comment by singhmansi25** [comment]
That's nice to hear.

**Comment by KKhushhalR2405** [comment]
> Its 90% done

Hi @SheetalChouhan12, just a suggestion. Do not make a PR with many changes. You can break your work into multiple parts if you think it is too heavy. Thank you

**Comment by SheetalChouhan12** [comment]
> > Its 90% done
> 
> Hi @SheetalChouhan12, just a suggestion. Do not make a PR with many changes. You can break your work into multiple parts if you think it is too heavy. Thank you

I just completed with issue , added the Django course on local system . I was making a PR but currently I don't know how to make PR in multiple parts .

**Comment by SheetalChouhan12** [comment]
@arpit456jain @KKhushhalR2405 @singhmansi25  I added the course but when run the server it showing list of errors and also "No Module named home"

**Comment by KKhushhalR2405** [comment]
Follow [this](https://github.com/arpit456jain/CodingEasy#project-setup)

**Comment by SheetalChouhan12** [comment]
> Follow [this](https://github.com/arpit456jain/CodingEasy#project-setup)

Done still showing same error

**Comment by KKhushhalR2405** [comment]
> Done still showing same error

Are you using the latest code? Do git pull and try again. And if you still get a error...kindly share the error image please

**Comment by SheetalChouhan12** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/90041130/159130090-10db9877-6b40-4950-9a9a-d762e9def274.png)

yes, I'm using the latest code. This is the error I'm getting.

**Comment by KKhushhalR2405** [comment]
No. You are not using the latest code. We have renamed the folder from `Home` to `home`. That's why you are getting the error.

**Comment by SheetalChouhan12** [comment]
Hey, @KKhushhalR2405 @arpit456jain  the issue itself has Label level 3 but in PR you mention label level 2, so my score in Leaderboard is 25 it should be 45. Please correct it to level 3 in PR. Thank you.
