### ISSUE TITLE
Adding more courses 

### ISSUE THREAD

**Issue by Muhammad-Galhoum** [arpit456jain/CodingEasy#175]
### Description

I will add a new **_Simple Course_** which is **jQuery**  

### Curriculum

1. Overview
2. Attributes and Content
3. Manipulating CSS

### Screenshots

![jQuery](https://user-images.githubusercontent.com/56798376/157461231-bb4b0501-f096-4fd1-ba56-eac608fbb38f.png)

**Comment by KKhushhalR2405** [comment]
Hi @Muhammad-Galhoum. We are working on making a template so that you can use it to add courses. We will update you when we are done. In meantime, you can start preparing the content and as soon as we provide the template, you can use it and make a Pull Request. Thank You

**Comment by KKhushhalR2405** [comment]
The templates are provided [here](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/SampleCourse) along with the instructions. If you are not familiar with Django, you can leave the URL mapping part and mention it in the PR, so someone else will do it. If you are familiar with Django, you can try mapping the URLs on your own. You can always ask for help on our discord channel. Assigning you the same.

**Comment by KKhushhalR2405** [comment]
And can you please break the issue into 2 separate PRs. Add first 3 topics, make a PR and get it merged and then work on the remaining topics. It would be hard for us to review so many changes. You will also get more points if you make more PRs😇😇

**Comment by Muhammad-Galhoum** [comment]
You wanna me to break this issue with only the first 3 topics and add another issue with the rest of the topics and you will assign me for them again? @KKhushhalR2405

**Comment by KKhushhalR2405** [comment]
Yes. 

> You wanna me to break this issue with only the first 3 topics and add another issue with the rest of the topics and you will assign me for them again? @KKhushhalR2405
