### ISSUE TITLE
Adding more courses 

### ISSUE THREAD

**Issue by Muhammad-Galhoum** [arpit456jain/CodingEasy#177]
### Description

**The rest of the jQuery Curriculum**

1. Manipulating DOM
2. Events
3. Effects

### Screenshots

![jQuery](https://user-images.githubusercontent.com/56798376/157551828-7da0f5fb-e301-4aeb-93ed-51d6a54b8075.png)

**Comment by KKhushhalR2405** [comment]
Hi @Muhammad-Galhoum. After you make a successful PR for #175, I will assign you with this issue😊. Thank you

**Comment by Muhammad-Galhoum** [comment]
Can u please assign me this issue please @KKhushhalR2405
