### ISSUE TITLE
Create a functional authentication system

### ISSUE THREAD

**Issue by ephemeralshay** [arpit456jain/CodingEasy#179]
### Description

Add following features to the app-
1. login page
2. register page
3. login required to access courses
4. password reset functionality
5. contact us form

Note - 
I plan to completely change the login and contact us page of the current project as they lack uniformity with the website.

**Comment by arpit456jain** [comment]
@ephemeralshay  
work on only login and sign up in this PR

do not implement password reset functionality and contact us form

**Comment by ephemeralshay** [comment]
Alright
