### ISSUE TITLE
Implement contact us feature

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#180]
### Description

store the details from contact us page to database only for now and give a msg of success or failure

**Comment by Muhammad-Galhoum** [comment]
Hi @arpit456jain, I wish u are fine
Can you please assign me to this issue

**Comment by vickyrules** [comment]
i want to contribute please assign it to me under GSSoc'22.

**Comment by Muhammad-Galhoum** [comment]
I'm the first person who asked to solve  the issue
please choose another issue @vickyrules 
please assign it to me @arpit456jain

**Comment by arpit456jain** [comment]
@Muhammad-Galhoum make PR within 2 days otherwise i have to assign it to @vickyrules

**Comment by Muhammad-Galhoum** [comment]
Ok, thanks @arpit456jain

**Comment by Arpana-Sharma** [comment]
hello, I wants to work on this issue
