### ISSUE TITLE
Steps are not in correct order in README

### ISSUE THREAD

**Issue by Rushijaviya** [arpit456jain/CodingEasy#183]
### Description

In the 'How to Make a Pull Request?' section of the README file step 3 and step 4 are not in order. 
Here we first need to go inside the CodingEasy folder and then we can set upstream.  Without going inside the folder of CodingEasy if we try to set upstream it gives an error 'fatal: not a git repository (or any of the parent directories): .git' . 

### Screenshots

![image](https://user-images.githubusercontent.com/59735978/158017247-141da431-983d-4849-a29b-6990be1cc03e.png)

**Comment by KKhushhalR2405** [comment]
Assigning you the same @Rushijaviya

**Comment by Muhammad-Galhoum** [comment]
@Rushijaviya  @KKhushhalR2405 
I have noticed this issue but I made the right solution and continued to do my task.
And there is an error also which is exists in the command add. , the solution is should be space between the word 'add' and the '.' symbol

**Comment by Rushijaviya** [comment]
Actually, I have already finished the work. I was exploring a project that's why I haven't done PR.
