### ISSUE TITLE
Link in footer

### ISSUE THREAD

**Issue by Rushijaviya** [arpit456jain/CodingEasy#187]
### Description

There is the link of [bootstrap](https://mdbootstrap.com/) in the footer of the home page. Is it added by mistake or added intentionally? There should be a link to Coding Easy. I would like to work on it.

### Screenshots

![image](https://user-images.githubusercontent.com/59735978/158336550-13a91f10-cade-47f9-9bd9-787e4b3f6155.png)

**Comment by KKhushhalR2405** [comment]
Hi @Rushijaviya, For this issue, I think you have to wait for some time. We are currently updating the footer part (#188). Till then, you can work on #189 if you wish to. Thank you
