### ISSUE TITLE
Add (up to-button) ▲ and update the footer and add a subscription email 

### ISSUE THREAD

**Issue by Muhammad-Galhoum** [arpit456jain/CodingEasy#188]

**Comment by singhmansi25** [comment]
@Muhammad-Galhoum 
Why you want to add link to GSSOC'22 with the Coding Easy website? Couldn't understand, Please Elaborate

**Comment by Muhammad-Galhoum** [comment]
## Only this is a suggestion, at least I will put  the link of this repo
## Can you assign me?
## @singhmansi25

**Comment by Muhammad-Galhoum** [comment]
## Ok thanks @arpit456jain

**Comment by Muhammad-Galhoum** [comment]
Do you want me to add any links for GSSoC ? @arpit456jain
