### ISSUE TITLE
Updating ReadMe of CodingEasy repository

### ISSUE THREAD

**Issue by singhmansi25** [arpit456jain/CodingEasy#189]
### Description

This is a beginner level issue.
There are some discrepancy in the repo like incorrect links for GSSOC'22.
So, anyone who is new to opensource can contribute to this issue.
Please explain in brief what all changes you will do in brief, so that we can assign you the issue.

**Comment by Muhammad-Galhoum** [comment]
## Can you assign this issue to me, please? @singhmansi25 
## I will edit all incorrect links as you want?

**Comment by singhmansi25** [comment]
@Muhammad-Galhoum 
I liked your spirit of contribution, but this issue has been created to introduce beginners with open source.
U can contribute to other issues. If no one is assigned, then we will assign you.

**Comment by singhmansi25** [comment]
**This issue is related to the github repository of Coding Easy and not with Coding easy website**

**Comment by Muhammad-Galhoum** [comment]
> If no one is assigned, then we will assign you.

## Can you assign me, please? @singhmansi25

**Comment by arpit456jain** [comment]
go ahead @Muhammad-Galhoum and do this asap

**Comment by singhmansi25** [comment]
Nice work @Muhammad-Galhoum
