### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by Rushijaviya** [arpit456jain/CodingEasy#190]
### Description

In the SVM section of Machine Learning, there is one image not loading. The image name in the HTML file and image name in img folder of static is different. There is one 's' missing in the image name. I would like to fix it.

### Screenshots

![image](https://user-images.githubusercontent.com/59735978/158428433-fa0b8e7e-9fb6-4ec1-918c-91464dee35c1.png)

**Comment by KKhushhalR2405** [comment]
Assigning you @Rushijaviya
