### ISSUE TITLE
Intention Error in python

### ISSUE THREAD

**Issue by Rushijaviya** [arpit456jain/CodingEasy#191]
### Description

There is a python Indentation error in the example of an open file.

### Screenshots

![image](https://user-images.githubusercontent.com/59735978/158431457-7cbba32e-48c8-4c2d-b919-754b0e6172d4.png)

**Comment by KKhushhalR2405** [comment]
You can first complete the issue which is already assigned to you. I will assign you this one later.

**Comment by Rushijaviya** [comment]
> You can first complete the issue which is already assigned to you. I will assign you this one later.

Sent PR for that issue. Now you can assign this one.

**Comment by KKhushhalR2405** [comment]
> Sent PR for that issue. Now you can assign this one.

I'll assign you once the PR is merged.

**Comment by KKhushhalR2405** [comment]
Assigning you @Rushijaviya
