### ISSUE TITLE
Integrating Hierarchical clustering

### ISSUE THREAD

**Issue by Jayanth-MKV** [arpit456jain/CodingEasy#193]
### Description

There is an issue with the hierarchical clustering module which is not linked properly to the machine learning module . This also includes the image associated with the hierarchical clustering module.

### Screenshots

![gssoc](https://user-images.githubusercontent.com/93820457/158553406-4ba21653-9b81-46d7-b1bc-06320b155472.png)

**Comment by KKhushhalR2405** [comment]
As an additional task, please remove `Hierarchical Clustering` from `template/home` and add it inside the `template/home/ML` folder and change the URLs accordingly. If you need any help, you can ask us on our discord channel. Assigning you

**Comment by Jayanth-MKV** [comment]
yeah made PR it once have a check @KKhushhalR2405 

> As an additional task, please remove `Hierarchical Clustering` from `template/home` and add it inside the `template/home/ML` folder and change the URLs accordingly. If you need any help, you can ask us on our discord channel. Assigning you
