### ISSUE TITLE
bot is not adding label in PR 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#197]
### Description

bot is not adding label in PR it should add gssoc'22  label when PR is created

**Comment by mr-palindrome** [comment]
I would like to work on this issue. But I will require a little bit of mentorship!

**Comment by singhmansi25** [comment]
@mr-palindrome 
Please update the progress of your work.

**Comment by singhmansi25** [comment]
@mr-palindrome 
**Do you want to work on this issue?
What mentorship you need??**

**Comment by mr-palindrome** [comment]
> @mr-palindrome **Do you want to work on this issue? What mentorship you need??**

Yes, I want to work on this but don't know how to set up a Github bot or make changes to it.

**Comment by singhmansi25** [comment]
@arpit456jain 
Please see this once

> > @mr-palindrome **Do you want to work on this issue? What mentorship you need??**
> 
> Yes, I want to work on this but don't know how to set up a Github bot or make changes to it.

**Comment by arpit456jain** [comment]
@mr-palindrome u can learn about Github actions from [here ](https://github.community/t/how-to-use-the-github-actions-bot/16535) or from ay other resource 

currently  this issue is not required if have any other suggestions in bot setting let us know
