### ISSUE TITLE
Adding reset password functionality

### ISSUE THREAD

**Issue by Muhammad-Galhoum** [arpit456jain/CodingEasy#203]
### Description

**I will Add reset password function to help the user from reset his/her password**

**Comment by Muhammad-Galhoum** [comment]
### Please assign this issue to me @arpit456jain

**Comment by mr-palindrome** [comment]
Can I work on this issue? As no one is assigned to it and also I made the user authentication system.
@arpit456jain

**Comment by arpit456jain** [comment]
@mr-palindrome for now i am assigning @Muhammad-Galhoum if he is unable to make PR in 2 to 3 days then can start work on it

**Comment by Muhammad-Galhoum** [comment]
**Thanks, @arpit456jain**
