### ISSUE TITLE
Improve UI of website 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#204]
### Description

Improve UI of whole website in multiple PRs

**Comment by srinjoy-26** [comment]
I would like to work on the navigation bar and a few styling regarding the home page.

**Comment by Manik-Aggarwal** [comment]
I would like to work on this issue, please assign it to me

**Comment by KKhushhalR2405** [comment]
Should we allow multiple people to work on this issue? @arpit456jain

**Comment by srinjoy-26** [comment]
yes it would be better if multiple people do small contributions , so as to get an amazing output

**Comment by arpit456jain** [comment]
No @KKhushhalR2405 assign them one by one and this should be one single issue for UI 
Give them 3 to 4 days otherwise assign issue to next one

**Comment by arpit456jain** [comment]
@srinjoy-26 go ahead

**Comment by arpit456jain** [comment]
@srinjoy-26 any updates ??

**Comment by srinjoy-26** [comment]
Sir I will make a pr day after tomorrow

**Comment by srinjoy-26** [comment]
> @srinjoy-26 any updates ??

Sir assign someone else , I am unable to figure out the files in the project , its getting very complex.

**Comment by arpit456jain** [comment]
@Manik-Aggarwal r u interested

**Comment by Manik-Aggarwal** [comment]
Yes

**Comment by Anjuli08** [comment]
I would like to work on this issue under GSSOC'22

**Comment by singhmansi25** [comment]
@Manik-Aggarwal 
Please update the status of your work

**Comment by singhmansi25** [comment]
@Anjuli08 
**What change you will be working on? 
Please specify, so that we can assign you.**

**Comment by Anjuli08** [comment]
I can work on the navbar and CSS of the home page if no changes are done on it yet

**Comment by arpit456jain** [comment]
@Anjuli08 go ahead

**Comment by ishashukla183** [comment]
I would like to work on this issue

**Comment by singhmansi25** [comment]
@ishashukla183 
**Please specify what changes you would add?**
