### ISSUE TITLE
html template does not exist bug 

### ISSUE THREAD

**Issue by amanbhardwaj12072003** [arpit456jain/CodingEasy#206]
### Description

when we click on the html course then it shows the error of "html template does not exist"

### Screenshots

![Screenshot from 2022-03-19 22-09-13](https://user-images.githubusercontent.com/95973608/159130204-6fe78fd9-8a5c-404c-bfdd-576e04b86399.png)

**Comment by amanbhardwaj12072003** [comment]
kindly assign this issue to me , i will work on this issue .

**Comment by arpit456jain** [comment]
@KKhushhalR2405 assign him if its a bug

**Comment by KKhushhalR2405** [comment]
Hi @amanbhardwaj12072003, The code is working fine on my system. I think you are facing a problem due to different OS

**Comment by amanbhardwaj12072003** [comment]
but when i made some changes then it worked just fine in mine too.
but its ok,thanks.

**Comment by KKhushhalR2405** [comment]
Thank you @amanbhardwaj12072003. You can look out for other issues to work on. Closing this one
