### ISSUE TITLE
Show the username with a welcome message before his/her name in the navigation bar when logging in and the navigation bar improvement

### ISSUE THREAD

**Issue by muhammadgalhoum** [arpit456jain/CodingEasy#207]
### Description

**In this Feature, I will show the username with a welcome message before his/her name in the navigation bar when logging in and improve the navbar to be more attractive**

**Comment by Muhammad-Galhoum** [comment]
**Please assign this issue to me @arpit456jain**

**Comment by KKhushhalR2405** [comment]
Assigning you @Muhammad-Galhoum
