### ISSUE TITLE
Personality Quiz

### ISSUE THREAD

**Issue by Asttttha** [arpit456jain/CodingEasy#228]
Personality Quiz using python 3, where time module is used.

https://github.com/Asttttha/Personality-Quiz-using-python-3/blob/main/personality.py

link of my project.

**Comment by singhmansi25** [comment]
Hey @Asttttha 
The quiz is mind-blowing.
But it would have been more attractive if you have tried making a GUI based GUIZ.
@arpit456jain 
Can you check if this fun-quiz can be the part of CodingEasy Project.

**Comment by arpit456jain** [comment]
@Asttttha sorry but its not related to this project
