### ISSUE TITLE
Integrating One Hot Encoding, K-Fold Cross Validation and Grid Search modules to ML course

### ISSUE THREAD

**Issue by Jayanth-MKV** [arpit456jain/CodingEasy#229]
### Description

Integrating One Hot Encoding, K-Fold Cross Validation and Grid Search modules to ML course
1. As the the html files are present but not connected to the machine learning course page I would like to connect them.
2.  Images of these files must be added to static folder.
3.  Images need to be connected with the files.
4.  Some UI changes have to be made such as extra list tags in the html files and extra quotes .
5. Images need to be added.

**Comment by singhmansi25** [comment]
@Jayanth-MKV 
**Please start working on the issue.**

**Comment by Jayanth-MKV** [comment]
Please add the level label
