### ISSUE TITLE
Improve read me

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#23]

**Comment by ssurbhi09** [comment]
Can I add how to contribute in readme section?

**Comment by arpit456jain** [comment]
Add content in this file 
https://github.com/arpit456jain/CodingEasy/blob/master/README.md

**Comment by ssurbhi09** [comment]
@arpit456jain I can only add how to contribute is it ohk?
Can I work now then assign me!

**Comment by arpit456jain** [comment]
Yes

**Comment by ssurbhi09** [comment]
@arpit456jain done 
Please add SWOC tag.

**Comment by arpit456jain** [comment]
@ssurbhi09

**Comment by ssurbhi09** [comment]
@arpit456jain yes?

**Comment by ssurbhi09** [comment]
@arpit456jain u didn't merge why?
Any problem?

**Comment by arpit456jain** [comment]
its  a issue @ssurbhi09 not a PR 😅 and that section how to contribute is already added
