### ISSUE TITLE
integrate a youtube section in pages 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#233]
### Description

take reference from here 
https://codewithharry.com/videos/tailwind-course-in-hindi-1/

idea is let say user go to HTML->basic tags so on that page there will be some documentation / a video section and a editor for testing the code

**Comment by arpit456jain** [comment]
@Jayanth-MKV before start working discuss it with mentors

**Comment by Jayanth-MKV** [comment]
Can you tell me how to proceed with this @arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker 
like, 
1. What are the things to be added 
2. How should it look like.
3. It would be better if some template is available for getting an idea on the UI
4. and Should this be done for each and every course ?

**Comment by singhmansi25** [comment]
@Jayanth-MKV 
Contributors can embed a youtube video in the corresponding course.
Take example as in GeeksforGeeks, you can watch videos.

**Comment by Jayanth-MKV** [comment]
@singhmansi25 okay

**Comment by Jayanth-MKV** [comment]
Is this okay. If you confirm i will make a PR   @arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker 
![Screenshot (411)](https://user-images.githubusercontent.com/93820457/161751866-736a6005-23c4-499c-96ba-32bc2277f48d.png)

**Comment by arpit456jain** [comment]
@Jayanth-MKV yeah looking good
 we can change the video  link dynamically right ?

**Comment by arpit456jain** [comment]
anyways make PR so that we can review
