### ISSUE TITLE
A separate page for listing our templates and downloading them

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#234]
### Description

I have 3 repos 
[Cool Front-End Templates](https://github.com/arpit456jain/Cool-Front-End_Templates)
[Amazing Css effects](https://github.com/arpit456jain/Amazing-Css-Effects)
[Amazing Js Projects](https://github.com/arpit456jain/Amazing-Js-Projects)

i want to fetch all the projects and list them here with a feature of downloading it
It should download the source code if template in zip file directly 

ping me discord server if any confusion because it might be confusing

**Comment by gurjeetsinghvirdee** [comment]
Assign me

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee

little bit busy on my exams, aur ye itni jaldi bnne wala issue ni h I need time or ek bar me PR bhi bnegi 2-3 baar me hoga

**Comment by arpit456jain** [comment]
i need some thing like this 
https://bootstrapmade.com/

**Comment by gurjeetsinghvirdee** [comment]
> i need some thing like this 
> https://bootstrapmade.com/

Ok I try to make same but in javascript

**Comment by arpit456jain** [comment]
@gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
Removing myself due to met an accident somedays before, now I can't sit or sleep like a normal person

**Comment by Jayanth-MKV** [comment]
@arpit456jain can u assign this to me

**Comment by Jayanth-MKV** [comment]
I would like to get much clarity on how the code has to be downloaded

**Comment by arpit456jain** [comment]
@Jayanth-MKV  check this website 
https://bootstrapmade.com/
