### ISSUE TITLE
change in mentor section

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#236]
### Description

change the mentors in 
mentors section of read me and add mentors under gssoc

**Comment by arpit456jain** [comment]
mentors are 
@singhmansi25 
@raghavTinker 
@KKhushhalR2405

**Comment by gurjeetsinghvirdee** [comment]
assign me

**Comment by muhammadgalhoum** [comment]
**Can you please assign this issue to me @arpit456jain**

**Comment by KKhushhalR2405** [comment]
Assigning you @gurjeetsinghvirdee
