### ISSUE TITLE
improvement in blog 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#241]
### Description

i want a blog system like this
https://geeksgod.com/category/internships/
in which i can post things related to various topics and generate urls and it should redirect to them

**Comment by muhammadgalhoum** [comment]
**I will build the blog section from Scratch because each time when I try to pull the changes from the master branch  I get the following error and I can not solve it** 

![error](https://user-images.githubusercontent.com/56798376/162629052-23953c22-3f0f-45a0-99f6-e55462e7441f.png)

### If you agree you can assign me @arpit456jain

**Comment by arpit456jain** [comment]
@muhammadgalhoum u have to run migrate command

run
py.exe manage.py makemigrations home
py.exe manage.py makemigrations  blog

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum u have to run migrate command
> 
> run py.exe manage.py makemigrations home py.exe manage.py makemigrations blog

### After running the last two commands and trying to access the admin panel I got the following error
![second error](https://user-images.githubusercontent.com/56798376/162631855-365ffc8a-70cb-4766-8170-222ada2709db.PNG)

**Comment by muhammadgalhoum** [comment]
**You can assign this issue to me @ @arpit456jain** 
**I will enhance the blog appearance and add post image features to the post (The user can add an image to the post or not)**
### But make sure it will take some days for me

**Comment by muhammadgalhoum** [comment]
Assign this issue to me please  @arpit456jain

**Comment by arpit456jain** [comment]
@muhammadgalhoum i need this kind of blog feature 
https://geeksgod.com/category/internships/

**Comment by arpit456jain** [comment]
@muhammadgalhoum u can call me through discord or we can have  a meet on sunday i want this issue to be done as soon as possible

**Comment by muhammadgalhoum** [comment]
I already working daily  on improving the blog and I will deliver asap
I had had an internet connection problem and I solved it
@arpit456jain

**Comment by arpit456jain** [comment]
ok @muhammadgalhoum just start making PRS so that we can review it

**Comment by muhammadgalhoum** [comment]
You forgot to close this issue @arpit456jain
