### ISSUE TITLE
Fully responsive cool looking navbar for the website

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#243]
### Description

no need to build it from scratch use bootstrap or u can take a navbar from any bootstrap template

**Comment by yash-25log** [comment]
hey if you just need a bootstrap navbar i am up for it

**Comment by yash-25log** [comment]
just tell me u need a side bar or menu bar which should be on top
or if you need dropdown or not

**Comment by yash-25log** [comment]
assign me in

**Comment by arpit456jain** [comment]
I need a navbar which looks good 
Just like the current navbar but UI should be great
Current navbar is very dull

**Comment by yash-25log** [comment]
ok bhaiya i will work on this and make a pr soon

**Comment by yash-25log** [comment]
@arpit456jain bhaiya where is home page html file

**Comment by yash-25log** [comment]
bhaiya pls share the link of the file where current navbar is
i need to replace it with another one
and i can't find that file

**Comment by arpit456jain** [comment]
base.html : https://github.com/arpit456jain/CodingEasy/blob/master/templates/home/base.html
navbar.html : https://github.com/arpit456jain/CodingEasy/blob/master/templates/includes/navbar.html

**Comment by arpit456jain** [comment]
@yash-25log

**Comment by yash-25log** [comment]
@arpit456jain currently there is no progress as i am at chandigarh university hack
i was busy with the project build at hackathon so will do it by wednesday/thursday

**Comment by arpit456jain** [comment]
@yash-25log update please?
