### ISSUE TITLE
Add video tutorials  

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#244]
### Description

u have to make video tutorials for the courses

watch this to understand the work flow : https://www.youtube.com/watch?v=SbRJZpReeh8&feature=youtu.be

tag me in discord server and let me know in which course u r interested

**Comment by muhammadgalhoum** [comment]
**Do you want to make a video for Coding Easy website to appear its features?
Please assign it to me @arpit456jain**

**Comment by arpit456jain** [comment]
@muhammadgalhoum first watch the video mentioned in description

**Comment by muhammadgalhoum** [comment]
Do you want me to choose the best video explaining each part of a particular course, or should I make a video for me while I explain a specific part? @arpit456jain

**Comment by arpit456jain** [comment]
U have to make a video tutorials
Check out videos present in Excel sheet
