### ISSUE TITLE
Make a our team page it should fetch details from json file or from database (it should be dynamically)

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#250]
### Description

it will contain  some sections like
1. Owner/founder
2. Mentors
3. Videos creators
4. content writers
5. Web developers
6. top contributors

**Comment by myhacktech** [comment]
sir i can do this ,if it involves fetching of data from mysql

**Comment by arpit456jain** [comment]
@myhacktech currently we will go with default database.
If you are interested let me know but i suggest you to focus on video tutorials because we want videos as much as possible ie a full playlist

**Comment by nikhil25803** [comment]
I can make an about us page that fetch data from a JSON file.
Can you please assign it to me?

**Comment by arpit456jain** [comment]
go ahead @nikhil25803

**Comment by arpit456jain** [comment]
@myhacktech i am proving u the data
kindly make a PR for that

**Comment by arpit456jain** [comment]
mentors : @raghavTinker @KKhushhalR2405 
video creators : @Ultimateutkarsh11 -> git github ,  @Shreya-spec : ML , @myhacktech  : CSS ,

**Comment by nikhil25803** [comment]
On it :)
