### ISSUE TITLE
Adding a Side Navigation Bar

### ISSUE THREAD

**Issue by BabyElias** [arpit456jain/CodingEasy#253]
### Description

Adding a side navbar for easier navigation of topics within a particular course. This would ensure smoother accessibility for the user as he/she can hover through the topics without having to move to the previous page.

**Comment by arpit456jain** [comment]
go ahead @BabyElias

**Comment by arpit456jain** [comment]
@BabyElias

**Comment by BabyElias** [comment]
Yup, I am working on it but am unable to see practically the changes that I have implemented because of not setting up the framework properly. I am trying to figure a way out. Give me 2-3 days, please.

**Comment by piyusha2001** [comment]
@arpit456jain  can you assign me this?

**Comment by singhmansi25** [comment]
GO AHEAD @piyusha2001

**Comment by arpit456jain** [comment]
@Jayanth-MKV do this asap

**Comment by Jayanth-MKV** [comment]
okay @arpit456jain
