### ISSUE TITLE
UI improvement 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#263]
### Description

improvement in UI of home page  and courses

**Comment by muhammadgalhoum** [comment]
please assign it to me and I will make More than one PR for this issue because of the number of courses @arpit456jain

**Comment by Jayanth-MKV** [comment]
Assign me @arpit456jain

**Comment by arpit456jain** [comment]
@muhammadgalhoum @Jayanth-MKV  
first let do the backend work which is more important now after that u both can work on this

**Comment by Jayanth-MKV** [comment]
okay @arpit456jain

**Comment by Jayanth-MKV** [comment]
# assign @arpit456jain

**Comment by muhammadgalhoum** [comment]
You can assign both of us and I will work on improving the home page @arpit456jain

**Comment by muhammadgalhoum** [comment]
Are you will assign this issue to me also? @arpit456jain

**Comment by arpit456jain** [comment]
@muhammadgalhoum sure

**Comment by muhammadgalhoum** [comment]
As I mentioned earlier @arpit456jain, I will work on developing the home page of the site

**Comment by arpit456jain** [comment]
OK @muhammadgalhoum

**Comment by arpit456jain** [comment]
@muhammadgalhoum  r u working on this ?

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum r u working on this ?

Yes, and it's about to be done, and I will do PR in a few minutes
@arpit456jain
