### ISSUE TITLE
small changes in blog

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#267]
### Description

changes required 
1. edit blog page should be only admin for now 
![image](https://user-images.githubusercontent.com/55352601/166427338-53cbe70a-5529-4c9f-acdf-d26ac4253527.png)

2 improve search functionality : 
-- add a button
-- show the search result like on the blog page

**Comment by arpit456jain** [comment]
@muhammadgalhoum  do this in one PR

and make one more PR for adding feature to comment on post by normal users

**Comment by muhammadgalhoum** [comment]
> ### Description
> changes required
> 
> 1. edit blog feature should be only admin for now
> 2. search functionality is not working
> 
> ### Screenshots
> _No response_

Search functionality is working successfully, you can search by title or content of any post

**Comment by muhammadgalhoum** [comment]
Do you want the admin only the person who can edit blog features using the Django admin panel? @arpit456jain

**Comment by arpit456jain** [comment]
> > ### Description
> > changes required
> > 
> > 1. edit blog feature should be only admin for now
> > 2. search functionality is not working
> > 
> > ### Screenshots
> > _No response_
> 
> Search functionality is working successfully, you can search by title or content of any post

if that things is not present then it should show **nothing to show**

**Comment by arpit456jain** [comment]
> Do you want the admin only the person who can edit blog features using the Django admin panel? @arpit456jain

my plan is to provide a role of staff only staff members should be able to edit blog

**Comment by arpit456jain** [comment]
but since there is not staff role right now if u can add that role well and good otherwise make it for admins only 
i mean if there are 2 or more admins 
they can edit all posts

**Comment by muhammadgalhoum** [comment]
> role
In this case, the following result will appear and there are no any links will appear on that page.

Do you want to change that message?

Do you want to change that message?![Capture](https://user-images.githubusercontent.com/56798376/166409449-bad63ccd-4e47-48dc-b414-63f22c9cac1f.PNG)

**Comment by muhammadgalhoum** [comment]
The admin can edit any post from the Django admin pannel
 @arpit456jain

**Comment by muhammadgalhoum** [comment]
> > > ### Description
> > > changes required
> > > 
> > > 1. edit blog feature should be only admin for now
> > > 2. search functionality is not working
> > > 
> > > ### Screenshots
> > > _No response_
> > 
> > 
> > Search functionality is working successfully, you can search by title or content of any post
> 
> if that things is not present then it should show **nothing to show**

In this case, the following result will appear and there are no any links will appear on that page.
Do you want to change that message? @arpit456jain 

Do you want to change that message?![Capture](https://user-images.githubusercontent.com/56798376/166409449-bad63ccd-4e47-48dc-b414-63f22c9cac1f.PNG)

**Comment by arpit456jain** [comment]
ok got it @muhammadgalhoum 

can u do one thing on result page show the post 
instead of 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/55352601/166412433-59a84891-c051-46e9-b785-7e3961ae48e1.png">

show this
<img width="553" alt="image" src="https://user-images.githubusercontent.com/55352601/166412458-b1d7ceed-f53a-435f-a06e-4217aa5198cb.png">

**Comment by arpit456jain** [comment]
and a button also for search like this 
https://codesmashersblog.herokuapp.com/myblog/

**Comment by arpit456jain** [comment]
> The admin can edit any post from the Django admin pannel @arpit456jain

yes i know that but currently any user is able to edit update or delete  the post with logged in

 please check

**Comment by muhammadgalhoum** [comment]
> the

I will try

**Comment by muhammadgalhoum** [comment]
> and a button also for search like this https://codesmashersblog.herokuapp.com/myblog/

I will try

**Comment by muhammadgalhoum** [comment]
> > The admin can edit any post from the Django admin pannel @arpit456jain
> 
> yes i know that but currently any user is able to edit update or delete the post with logged in
> 
> please check

No, Only the post or Category owner can  edit or delete his/her own posts or category

**Comment by muhammadgalhoum** [comment]
In this issue, I will improve the search result and the search form and please put level 2  or level 3 on it 
And the issue for determining the roles of admin and users will be in a separate PR and put level 3 on it 
Are you agree @arpit456jain?

**Comment by arpit456jain** [comment]
> > > The admin can edit any post from the Django admin pannel @arpit456jain
> > 
> > 
> > yes i know that but currently any user is able to edit update or delete the post with logged in
> > please check
> 
> No, Only the post or Category owner can edit or delete his/her own posts or category

when i tried i was not logged in and it allows me to to it

**Comment by arpit456jain** [comment]
> In this issue, I will improve the search result and the search form and please put level 3 on it And the issue for determining the roles of admin and users will be in a separate PR and put level 3 on it Are you agree @arpit456jain?

ok

**Comment by muhammadgalhoum** [comment]
> when i tried i was not logged

Impossible, Make a short video to show me

**Comment by muhammadgalhoum** [comment]
> > In this issue, I will improve the search result and the search form and please put level 3 on it And the issue for determining the roles of admin and users will be in a separate PR and put level 3 on it Are you agree @arpit456jain?
> 
> ok

Please, edit the description of this issue

**Comment by muhammadgalhoum** [comment]
And assign this issue to me after updating the issue description @arpit456jain

**Comment by arpit456jain** [comment]
> > when i tried i was not logged
> 
> Impossible, Make a short video to show me

this page should not open by any normal user
![image](https://user-images.githubusercontent.com/55352601/166427226-bcfa1866-42b9-473c-aec4-9aafd2ac078e.png)

**Comment by arpit456jain** [comment]
@muhammadgalhoum  i had updates the PR description 
if its not clear yet let me know we will discuss it on meet 
otherwise if its clear 
do this changes after the PR gets merged which is opened now of another user

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum i had updates the PR description if its not clear yet let me know we will discuss it on meet otherwise if its clear

As I mentioned earlier, and you agreed to that, I will do 2 PR. The first PR will be to solve the second problem in the description of this issue, which is to modify the search form, as well as the result of the search and the other PR will be in which the role will be determined for both the normal user and the admin, and you will put level 3 on each
Is that true and do you agree with it? @arpit456jain

**Comment by arpit456jain** [comment]
in 2. u just have to write one line 
if user is admin 
show that button for going to edit page
else 
don't show


in 1.
u have to add a button 

the main things is to display the search result as the blog page which should be of lvl2 but i am giving lvl3 on this PR and will give suitable labels on next Prs of urs

**Comment by muhammadgalhoum** [comment]
> in 2. u just have to write one line if user is admin show that button for going to edit page else don't show
> 

Why do you hesitate in your words? Didn't you earlier agree that I would do 2 PR?

The solution to this part of this issue will not be one line?
If you know a way to solve this issue in one line, please put it here in a comment and I will make one PR otherwise I will make 2 PR because I work hard and diligently, and no one changes my code after writing it, as I do in other people's codes

**Comment by arpit456jain** [comment]
Ok make 2 PRs lvl 2 on both

**Comment by muhammadgalhoum** [comment]
> Ok make 2 PRs lvl 3 for improving search feature and lvl2 on for role

Ok

**Comment by arpit456jain** [comment]
@muhammadgalhoum  now make a PR for role it will be of lvl3 but make sure of these things

1. update ur repo
2. branch shoule be updated
3. admin can edit,delete any post or add it
4. people having role of staff can make post , edit or delete from website
