### ISSUE TITLE
templates of css and js not showing

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#269]
### Description

1.templates of css and js not showing
2.all templates of cool front are also not showing

**Comment by arpit456jain** [comment]
@Jayanth-MKV

**Comment by Jayanth-MKV** [comment]
Yes assign it to me @arpit456jain

**Comment by arpit456jain** [comment]
@Jayanth-MKV do this asap

**Comment by arpit456jain** [comment]
@Jayanth-MKV i just noticed that u have hard coded the templates 
instead of that either use a json file or directly fetch it from the respective repo

**Comment by arpit456jain** [comment]
u have to use this somehow otherwise its very difficult for handling for us
https://github.com/arpit456jain/Cool-Front-End-Templates/blob/master/style_links.json
or 
https://raw.githubusercontent.com/arpit456jain/Cool-Front-End-Templates/master/style_links.json

**Comment by arpit456jain** [comment]
if its not possible to use directly just download this json file and use it

**Comment by Jayanth-MKV** [comment]
okay sure i would in that way only
