### ISSUE TITLE
add routes for C course 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#271]
### Description

templates for C course are there 
add routing for it

**Comment by soumali28** [comment]
I would Like to work on this issue under Gssoc.

**Comment by arpit456jain** [comment]
@soumali28  do this and make PR before tomorrow morning

**Comment by soumali28** [comment]
Hey  @arpit456jain  it wont be possible to do it by tonight cuz m actually out now so if its urgent you can assign someone else.

**Comment by muhammadgalhoum** [comment]
You can assign it to me if she can't @arpit456jain

**Comment by muhammadgalhoum** [comment]
Plz, assign this issue to me  @arpit456jain

**Comment by Atif0604** [comment]
Please Assign Me @arpit456jain under GSSOC'22

**Comment by muhammadgalhoum** [comment]
I asked @arpit456jain to assign this issue to me before you @Atif0604 
Please assign this issue to me and I will solve it asap

**Comment by muhammadgalhoum** [comment]
Plz, assign this issue to me and I will solve it asap @arpit456jain

**Comment by arpit456jain** [comment]
ok @muhammadgalhoum

**Comment by singhmansi25** [comment]
@muhammadgalhoum and @Atif0604 
Please don't argue for getting assigned, we will assign contributors on the basis of First come first serve. If any assigned contributor fails to complete, we will assign the other person.

> I asked @arpit456jain to assign this issue to me before you @Atif0604 Please assign this issue to me and I will solve it asap

**Comment by muhammadgalhoum** [comment]
I think so too, but I assure you that I came first @singhmansi25
