### ISSUE TITLE
Images not loading properly

### ISSUE THREAD

**Issue by Susmita-Dey** [arpit456jain/CodingEasy#272]
### Description

I just visited the website and saw that some images are not getting loaded in the website and this needs to be fixed.

**I'm a GSSoC'22 contributor. Kindly assign this issue to me.**

### Screenshots

![image](https://user-images.githubusercontent.com/79099734/166484494-5305a968-6a9f-4c3a-81b3-d7c25b10d46b.png)

**Comment by arpit456jain** [comment]
@Susmita-Dey do it asap

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey do it asap

Okay

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey 
> Any updates? 

I'll create the PR tomorrow morning. It's almost done.

**Comment by Susmita-Dey** [comment]
@arpit456jain I created the environment locally on my computer and it's working perfectly but I think there's some issue with the Heroku app for loading the images. Because the code is working correctly in **localhost**.

## Localhost preview
![image](https://user-images.githubusercontent.com/79099734/167245664-7bcba793-5dbf-407e-b643-5c39d6294f6d.png)

## Heroku website preview 
![image](https://user-images.githubusercontent.com/79099734/167245697-c72016a9-e1df-4920-bdd8-63e605e32b21.png)

---

📝**Suggestion**:- Try to host in some other server other than Heroku and check if it's working perfectly there or not.
