### ISSUE TITLE
Navbar content is not displaying properly

### ISSUE THREAD

**Issue by Kunal0220** [arpit456jain/CodingEasy#287]
### Description

The navbar content is piling over one another which is hampering the UI . I would like to fix it and make some further enhancements to improve the UI of the website in terms of navbar .

### Screenshots

<img width="1428" alt="Screenshot 2022-05-06 at 8 17 22 PM" src="https://user-images.githubusercontent.com/71934168/167160655-77fef0c4-19ac-431a-ba6c-7b89fe0e7555.png">

**Comment by Kunal0220** [comment]
Please add GSSoC tag and level to it.

**Comment by sonalee21** [comment]
Hello Sir,
I would like to work on this issue, please assign it to me.

**Comment by KKhushhalR2405** [comment]
Hi @Kunal0220 @sonalee21, Thank you for raising the issue. But the navbar looks good to me.

![image](https://user-images.githubusercontent.com/58569950/167245026-2940d57e-ee04-44e6-9412-e46084380025.png)

 I believe it is a problem with the hosting service. I will look into it and if any changes are required, I would assign them to you. Thanks

**Comment by arpit456jain** [comment]
@Kunal0220 go ahead

**Comment by Kunal0220** [comment]
Aye aye captain!

**Comment by arpit456jain** [comment]
@Kunal0220 i just notice that the navbar is correct in local system but its not in hosted version because some css is not rendering properly so if u have any idea about it go on it

**Comment by Kunal0220** [comment]
Ok @arpit456jain , let me exercise with the code for sometime and then I'll revert back .

**Comment by Kunal0220** [comment]
Hi @arpit456jain , My exams got over yesterday and I my trying to go about it . I figured out the problem by inspecting it but m not being able to make it run on my local system . Some issues with the dependencies 🥲. 

Should I provide the solution so that someone can fix it ?

**Comment by arpit456jain** [comment]
sure

**Comment by arpit456jain** [comment]
> Hi @arpit456jain , My exams got over yesterday and I my trying to go about it . I figured out the problem by inspecting it but m not being able to make it run on my local system . Some issues with the dependencies 🥲.
> 
> Should I provide the solution so that someone can fix it ?

make sure to make a virtual env

**Comment by Kunal0220** [comment]
I tried all the possible techniques for my end , But i'll give one more try , if it works then fine , or else I will type down the solution here itself.

**Comment by Kunal0220** [comment]
Thanx for the time @arpit456jain , really appreciated . I am unassigning myself so that someone can take this over and make it right.

**Comment by DhairyaWankhade** [comment]
I'm GSSoC22 Contributor, Please assign this issue to me.

**Comment by arpit456jain** [comment]
ok @DhairyaWankhade  
but let me clear a thing navbar looks perfect in local system its giving problem with hosted one

**Comment by arpit456jain** [comment]
@DhairyaWankhade updates ?

**Comment by DhairyaWankhade** [comment]
Is this issue resolved..??
