### ISSUE TITLE
Integrating IDE in the website

### ISSUE THREAD

**Issue by nikhil25803** [arpit456jain/CodingEasy#291]
### Description

I want to imbed an online IDE in the website for the language Python. So that we can show code in proper format users can have a better user experience and they can have hands-on experience too. 

### Sample View

[![image](https://www.linkpicture.com/q/preview_3.png)](https://www.linkpicture.com/view.php?img=LPic62766d22931e6460503937)

**Comment by arpit456jain** [comment]
go ahead @nikhil25803 
make a template for it and inherit in all pages

**Comment by arpit456jain** [comment]
@nikhil25803  add this ide in C course as well

**Comment by arpit456jain** [comment]
yup i know but no worries just add it
and yeah someone added link to topics of cpp course for some topics in C 
remove them and make a septate page for it

**Comment by arpit456jain** [comment]
can u do it @nikhil25803

**Comment by nikhil25803** [comment]
I will embed the IDE in the C language and will try to fix the link issue. I will ping you on discord if face any problems.

**Comment by arpit456jain** [comment]
ok sure
