### ISSUE TITLE
add a role of staff

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#294]
### Description

There are 3 types of people 
1. Admins : have all the access
2. Staff (for now technical writer): can change,edit post , update it from website only , admin panel should not be accessible 
3. normal users : only read the post

**Comment by arpit456jain** [comment]
@muhammadgalhoum u just have to add a role staff

**Comment by muhammadgalhoum** [comment]
OK, I will try to solve it

**Comment by arpit456jain** [comment]
@muhammadgalhoum do this asap and then u can work on comments and reply for blog

**Comment by muhammadgalhoum** [comment]
I've been working on this problem since yesterday and will make a PR for it  asap @arpit456jain
