### ISSUE TITLE
wrong url in our team

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#295]
### Description

some links are wrong

in facebook icon link of GitHub is opening

**Comment by arpit456jain** [comment]
@nikhil25803 correct it

**Comment by nikhil25803** [comment]
I have replaced the Facebook icon with GitHub! Now it's fine.
As everyone does not have a Facebook account, I have added LinkedIn, GitHub, and Twitter only. Do I need to add the Facebook links too or make a PR as it is now only?
