### ISSUE TITLE
add to favorite 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#299]
### Description

Add a feature to add a template in favorite/wishlist of user

**Comment by muhammadgalhoum** [comment]
please, assign it to me

**Comment by singhmansi25** [comment]
@muhammadgalhoum 
What's the update?

**Comment by muhammadgalhoum** [comment]
I'm already about to finish solving this problem and will do a PR ASAP @singhmansi25

**Comment by muhammadgalhoum** [comment]
> in this issue i want a feature to add templates in wishlist

Ok, Please put level 3 on it
Thanks in advanced
