### ISSUE TITLE
Improve UI of website

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#3]

**Comment by woterr** [comment]
yeah i dont know the website URL as https://coding-easy.netlify.app isnt actually working, if i look at the current UI, i could prossibly update it

![image](https://user-images.githubusercontent.com/83902185/152690329-6c60031c-f415-47fa-b007-760f3feade32.png)

**Comment by arpit456jain** [comment]
Actually it has been migrated to django u have to run it on local system

**Comment by kalashvasaniya** [comment]
Hey, I want to work on this issue!

**Comment by Sakshi-Gupta06** [comment]
I want to work on the design part of the website.
please assign me

**Comment by nikhil25803** [comment]
Thank You. On it!

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by saketsagarsingh** [comment]
@arpit456jain  I want to work on this issue as I have hands on experience on UI, please assign this issue to me under gssoc'22

**Comment by singhmansi25** [comment]
@nikhil25803 
What's the status of your work?
