### ISSUE TITLE
Add video Solutions for Leetcode

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#301]
### Description

Make videos for Leetcode
1. Explain the problem statement
2. write the brute force approach 
3. write efficient approach
4. upload this video on google drive
5. save both the codes in a text file and in last add the link of video
6. Make PR

**Comment by Sabyasachi-Seal** [comment]
I can do this one. Please assign.

**Comment by Shreya-spec** [comment]
Hi, please assign me this issue

**Comment by TusharKesarwani** [comment]
Hi, please assign me this issue

**Comment by TusharKesarwani** [comment]
This is a demo video of array question of leetcode:-
https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk

**Comment by sohan2503001** [comment]
Hi can you assign me this issue

**Comment by riyaroy2086** [comment]
Hi, please assign me this issue

**Comment by arpit456jain** [comment]
@sohan2503001  and @riyaroy2086 please share a sample videos first 
for reference : https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk

**Comment by riyaroy2086** [comment]
> @sohan2503001 and @riyaroy2086 please share a sample videos first for reference : https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk

Demo video of array question of Leetcode:-
https://drive.google.com/file/d/1Fn-1GnQWecL5Ua53Dwa5ZM3xOL4YLLoa/view?usp=drivesdk

**Comment by sohan2503001** [comment]
> @sohan2503001 and @riyaroy2086 please share a sample videos first for reference : https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk

> Demo Video of Contains Duplicate
https://drive.google.com/file/d/1k_NKKYKrGdLmFa2m0RP3DRg651vbWcqn/view?usp=sharing

**Comment by arpit456jain** [comment]
> > @sohan2503001 and @riyaroy2086 please share a sample videos first for reference : https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk
> 
> Demo video of array question of Leetcode:- https://drive.google.com/file/d/1Fn-1GnQWecL5Ua53Dwa5ZM3xOL4YLLoa/view?usp=drivesdk

u have to explain the problem statement and approach also see this
https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk

**Comment by arpit456jain** [comment]
> > @sohan2503001 and @riyaroy2086 please share a sample videos first for reference : https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk
> 
> > Demo Video of Contains Duplicate
> > https://drive.google.com/file/d/1k_NKKYKrGdLmFa2m0RP3DRg651vbWcqn/view?usp=sharing

yeah @sohan2503001 its fine u can make PR
u have to add 2 videos in one PR there will be 2 text file in which u will add ur code and drive link

**Comment by riyaroy2086** [comment]
> > > @sohan2503001 and @riyaroy2086 please share a sample videos first for reference : https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk
> > 
> > 
> > Demo video of array question of Leetcode:- https://drive.google.com/file/d/1Fn-1GnQWecL5Ua53Dwa5ZM3xOL4YLLoa/view?usp=drivesdk
> 
> u have to explain the problem statement and approach also see this https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk

Demo video : https://drive.google.com/file/d/1bdj7RnmpIk0SmTD9EN9F-xwixIXZszgu/view?usp=drivesdk

**Comment by arpit456jain** [comment]
> > > > @sohan2503001 and @riyaroy2086 please share a sample videos first for reference : https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk
> > > 
> > > 
> > > Demo video of array question of Leetcode:- https://drive.google.com/file/d/1Fn-1GnQWecL5Ua53Dwa5ZM3xOL4YLLoa/view?usp=drivesdk
> > 
> > 
> > u have to explain the problem statement and approach also see this https://drive.google.com/file/d/1EvrNKz4HpDUIjk87hJk9u_61anFdkjbe/view?usp=drivesdk
> 
> Demo video : https://drive.google.com/file/d/1bdj7RnmpIk0SmTD9EN9F-xwixIXZszgu/view?usp=drivesdk

Yeah now its fine just increase your voice rest all is ok
U can make PR by adding 2 video

**Comment by psorat307** [comment]
Hi, please assign me this issue

**Comment by psorat307** [comment]
#448

**Comment by psorat307** [comment]
Added video solution of Leetcode Question 
Please review this pull request #448

**Comment by harshb910** [comment]
Hi, please assign me this issue.

**Comment by harshb910** [comment]
Please review pull request #454.
