### ISSUE TITLE
Add remaining documentation of python course 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#306]
### Description

Add 4 topics one PR lvl2 or 3 depends on content and time

**Comment by muhammadgalhoum** [comment]
Please, assign it to me and I will make a PR asap and give me level 3, are you agree?

**Comment by arpit456jain** [comment]
Ok but maintain the quality of content 
Do not copy paste from anywhere
If possible improve the current documentation

**Comment by muhammadgalhoum** [comment]
Ok, I will not make copy and paste from anywhere @arpit456jain 
Please, assign it to me to start working on it

**Comment by muhammadgalhoum** [comment]
Please, close this issue@arpit456jain

**Comment by muhammadgalhoum** [comment]
Please close this issue too @KKhushhalR2405
