### ISSUE TITLE
Want to add more resources for Git

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [arpit456jain/CodingEasy#308]
### Description

The Information given for git is very less and just covers the basics. 

I want to add more stuff and make it a full course so that no one is stuck while using the commands or while getting started with git.

**Comment by arpit456jain** [comment]
sure @Sabyasachi-Seal first add documentation for these topics and explain it well 
git init
git status
git add
git commit
git log
git switch
git branch
git diff
git reset
git show
git merge
git remote
git checkout
git push
git pull
git stash

we are also making video tutorials so try to  co-relate with it
https://www.youtube.com/watch?v=WD5Un8e3EXQ&list=PLq48nQVMAPYF9r0XptDZRvv52cHO6N-h5

**Comment by Sabyasachi-Seal** [comment]
Thanks a lot for assigning! 
Will get to work right away.

Sure will try to corelate with the videos and make the documentation accordingly.

**Comment by Sabyasachi-Seal** [comment]
Some of the commands in the list : e.g, add, commit and status already have thier documentation. Do I need to add more? @arpit456jain

**Comment by singhmansi25** [comment]
Yes @Sabyasachi-Seal if possible do add more content. You can refer to this: [https://github.com/git-guides/git-add](https://github.com/git-guides/git-add)
If you have any further query, then do drop a message.

**Comment by Sabyasachi-Seal** [comment]
> Yes @Sabyasachi-Seal if possible do add more content. You can refer to this: [https://github.com/git-guides/git-add](https://github.com/git-guides/git-add)
> If you have any further query, then do drop a message.

Do I need to add the sections for every command ??? Because then there will be over 20 sections. The current system is good and if I add more commands and update the info on it with updated documentation then I think that will be good.

**Comment by singhmansi25** [comment]
@arpit456jain 
Please check this once

**Comment by arpit456jain** [comment]
@Sabyasachi-Seal u can add multiple topics on one page as u wish

**Comment by Sabyasachi-Seal** [comment]
> @Sabyasachi-Seal u can add multiple topics on one page as u wish

Ok got it. Thanks for the clarification.

**Comment by arpit456jain** [comment]
@Sabyasachi-Seal   r u going to get add more documentation ?

**Comment by Sabyasachi-Seal** [comment]
> @Sabyasachi-Seal   r u going to get add more documentation ? 

Could you suggest what more to add ?

**Comment by Sabyasachi-Seal** [comment]
Okay @arpit456jain . Will I send the new PR to this issue only?

**Comment by arpit456jain** [comment]
yes @Sabyasachi-Seal

**Comment by arpit456jain** [comment]
@Sabyasachi-Seal  as u can check currently there are only 3 subtopics in website and we have integrate videos of them 

We have around 20+ videos now so i want subtopics of thoise videos so that we can integrate those videos on website

**Comment by arpit456jain** [comment]
@Sabyasachi-Seal make PR asap

**Comment by Sabyasachi-Seal** [comment]
> @Sabyasachi-Seal make PR asap 

actually my exams are going on, will it be possible to add someone who can help out ?

**Comment by arpit456jain** [comment]
sure @Sabyasachi-Seal

**Comment by arpit456jain** [comment]
@nikhil25803 can u do this ?

**Comment by nikhil25803** [comment]
@arpit456jain Yes Bhaiya, I can

**Comment by arpit456jain** [comment]
@nikhil25803

**Comment by nikhil25803** [comment]
On it Bhaiya, will make the PR till tomorrow morning :)
