### ISSUE TITLE
Improve the documentation of C++ course

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#310]
### Description

![image](https://user-images.githubusercontent.com/55352601/167646877-9be6d5bd-c988-4dd2-b1b3-761b2e7e4333.png)
![image](https://user-images.githubusercontent.com/55352601/167646927-e431a5fd-0a1a-46ad-ab66-624c6c595a7f.png)

other courses documentation is much better 
![image](https://user-images.githubusercontent.com/55352601/167647025-bb093c80-fab5-44cb-b8cb-01e66b22f9a6.png)

**Comment by void-ness** [comment]
Hello, I would like to work upon the above issue and improve the content. can you kindly assign it to me please? to get started if you can help me file path of the above mentioned webpage, it will be really helpful
thank you

**Comment by arpit456jain** [comment]
@void-ness  this is path of C course
  https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/CPP

run it on local system and in templates/home/CPP u will find all the files

**Comment by void-ness** [comment]
Thank you for assigning it to me. I will get back to you with the assigned work soon.

**Comment by void-ness** [comment]
Thank You! as per the mentioned Description I have submitted the requested changes. Kindly check them out at #327.

I would love to contribute more in the future. Your guidance regarding file path proved to be very helpful for me. I am a GSSoC contributor and would love if you can add the level label to my contribution too. Thank You

**Comment by arpit456jain** [comment]
@void-ness it would be great if u could make videos tutorials on C++
or videos for leetcode solutions
