### ISSUE TITLE
Add documentation For C course

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#311]
### Description

Add content for all topics in C course

**Comment by Atif0604** [comment]
May i work on this

**Comment by singhmansi25** [comment]
Go ahead @Atif0604

**Comment by shahnehal0407** [comment]
I would like to work on this.

**Comment by singhmansi25** [comment]
@shahnehal0407 
If the assigned contributor is unable to work then we will assign you for this issue.

**Comment by singhmansi25** [comment]
@Atif0604 
What's the update of your work?

**Comment by Atif0604** [comment]
> @Atif0604 What's the update of your work?

working on it
but i had a ques like there are many subtopics so should i make every subtopic a PR or all subtopics in 1 PR

**Comment by singhmansi25** [comment]
If you are adding bigger subtopics you can make a new PR for that @Atif0604

**Comment by arpit456jain** [comment]
> > @Atif0604 What's the update of your work?
> 
> working on it but i had a ques like there are many subtopics so should i make every subtopic a PR or all subtopics in 1 PR @arpit456jain @singhmansi25

try to add subtopics as much as possible in one PR level will be decided on the basis of work

**Comment by arpit456jain** [comment]
@Atif0604 make PR asap and add topics as much as possible in PR instead of making multiple PRs since very less time left
