### ISSUE TITLE
Error in Documentation of Readme

### ISSUE THREAD

**Issue by Kunal0220** [arpit456jain/CodingEasy#316]
### Description

In the Readme , in [How to Make A Pull Request](https://github.com/arpit456jain/CodingEasy#how-to-make-a-pull-request) section , Point 4 , The command to add upstream url is given as : 
` git remote add upstream https://github.com/arpit456jain.git ` 
instead if should be : 
` get remote add upstream https://github.com/arpit456jain/CodingEasy.git `

I can correct it and make a PR.
Under[GSSoC22']

### Screenshots

<img width="524" alt="Screenshot 2022-05-13 at 1 51 46 PM" src="https://user-images.githubusercontent.com/71934168/168242215-be1d55c3-a985-420e-993e-d3fe59c9a37b.png">

**Comment by Kunal0220** [comment]
Should I make a PR @arpit456jain ?????

**Comment by singhmansi25** [comment]
Yes you can @Kunal0220 
Your contribution can be counted as Level0.
If its ok @arpit456jain

**Comment by Kunal0220** [comment]
Hi ma'am , even if he doesn't specify any level its ok . Its just making this repo better for the community members.🙌🏻
