### ISSUE TITLE
Add a feature to comment on blog post for normal user

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#319]
### Description

Add a feature to comment on blog post for normal user the username of user should show
and when admin make a comment it admin should show

**Comment by arpit456jain** [comment]
@muhammadgalhoum r u interested ?

**Comment by muhammadgalhoum** [comment]
Yes, I'm interested in solving this problem but after completing the development of the home page, I will solve this problem 
So, assign it to me  @arpit456jain
