### ISSUE TITLE
Add more Courses 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#32]
make a  separate issue and describe which course are going to add

**Comment by astha2412** [comment]
Adding C course.....Plz assign @arpit456jain

**Comment by SheetalChouhan12** [comment]
@arpit456jain Please assign the role for Adding Django course

**Comment by arpit456jain** [comment]
go ahead @SheetalChouhan12

**Comment by Aman16-ai** [comment]
Please assign me for the java course

**Comment by diptishegar** [comment]
@arpit456jain please assign me the role for adding React Js course.

**Comment by Suvodeep-Das** [comment]
Full Name: Suvodeep Das
GitHub Profile Link: https://github.com/Suvodeep-Das
Objective: I want to add machine learning concepts related to One Hot Encoding, K-Fold Cross Validation, Gridsearch, and Naive Bayes.
GSSoC'22 Participant.

I would like to work on this issue.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by suman-shah** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by arpit456jain** [comment]
> Full Name: Suvodeep Das GitHub Profile Link: https://github.com/Suvodeep-Das Objective: I want to add machine learning concepts related to One Hot Encoding, K-Fold Cross Validation, Gridsearch, and Naive Bayes. GSSoC'22 Participant.
> 
> I would like to work on this issue.

create  a new issue for that and start working

**Comment by arpit456jain** [comment]
> @arpit456jain Please assign the role for Adding Django course

create a new issue
