### ISSUE TITLE
Add yt videos in git github course properly and add documentation

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#359]
### Description

we have a playlist on youtube of git github videos
we want to integrate those videos in website and add documentation also if required

**Comment by muhammadgalhoum** [comment]
Please assign it for me @arpit456jain

**Comment by arpit456jain** [comment]
go ahead @muhammadgalhoum

**Comment by arpit456jain** [comment]
@muhammadgalhoum first make a small PR just integrate 2 videos only it will be of lvl 0 after that do the rest of work

**Comment by arpit456jain** [comment]
take videos links from here 
https://www.youtube.com/watch?v=WD5Un8e3EXQ&list=PLq48nQVMAPYF9r0XptDZRvv52cHO6N-h5

**Comment by muhammadgalhoum** [comment]
Please give me the playlist and explain what you want

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum first make a small PR just integrate 2 videos only it will be of lvl 0 after that do the rest of work

Please put level 1 for these 2 videos 
OK?

**Comment by arpit456jain** [comment]
ok

**Comment by muhammadgalhoum** [comment]
close this issue too after merging its PR @arpit456jain
