### ISSUE TITLE
Add content for remaining topics in C++ course

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#360]
### Description

1. add topics as much as possible in one PR 
2. maintain the quality

**Comment by piyusha2001** [comment]
@arpit456jain  I want to work on this . Can you please assign me this issue?

**Comment by arpit456jain** [comment]
@piyusha2001 go ahead and make PR as soon as possible

**Comment by arpit456jain** [comment]
@piyusha2001 if u interested in making video tutorials for C++ course create a new issue for it
