### ISSUE TITLE
improvements required in cards

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#361]
### Description

remove the flip  of cards and make the cards little bit small and add the text below img
 like this
<img width="199" alt="image" src="https://user-images.githubusercontent.com/55352601/169707135-26747254-18c5-441f-afdf-99f84a8f1dfa.png">

**Comment by arpit456jain** [comment]
@muhammadgalhoum

**Comment by muhammadgalhoum** [comment]
OK, assign it to me @arpit456jain

**Comment by muhammadgalhoum** [comment]
close this issue @arpit456jain
