### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by Jayanth-MKV** [arpit456jain/CodingEasy#364]
### Description

1. No common styling among all the modules of python course.
2. No proper indentation.
3. Font alignment didn't match.
4. Modules headings are all in different manner ( No common styling ).

These are all the issues with the UI in  python course.
![Screenshot (438)](https://user-images.githubusercontent.com/93820457/169725385-b6ca6248-b9ba-4b58-a6b6-3b04f3ab8c00.png)
![Screenshot (439)](https://user-images.githubusercontent.com/93820457/169725394-4d2449ed-bea1-4c4a-bc93-3e47b1965d4d.png)
![Screenshot (440)](https://user-images.githubusercontent.com/93820457/169725397-1385ef02-3f87-4943-8d99-8828bbbb108f.png)
![Screenshot (441)](https://user-images.githubusercontent.com/93820457/169725405-b72941d8-6fdd-4012-9761-efd834b64491.png)

**Comment by Jayanth-MKV** [comment]
@arpit456jain could you tell me which of the last two screenshots is the correct heading format.

**Comment by KKhushhalR2405** [comment]
![image](https://user-images.githubusercontent.com/58569950/169789416-fcb7284f-a904-4db4-a580-da32a08ebb69.png)


This one @Jayanth-MKV
