### ISSUE TITLE
No Proper structure in ML course and improving the navbar dropdown

### ISSUE THREAD

**Issue by Jayanth-MKV** [arpit456jain/CodingEasy#366]
### What would you like to share?

Proper structuring of data is  required in ML course
navbar dropdown needs to be improved.
![Screenshot (443)](https://user-images.githubusercontent.com/93820457/169727613-8ccad2f7-310b-4a0b-840f-fcca2e675e2a.png)

![Screenshot (440)](https://user-images.githubusercontent.com/93820457/169726231-b2fd8fb6-4199-4a90-bec3-96b6162e8b66.png)
![Screenshot (443)](https://user-images.githubusercontent.com/93820457/169726236-9f63263e-12f3-4487-88b7-0c300a025893.png)

**Comment by singhmansi25** [comment]
go ahead @Jayanth-MKV
