### ISSUE TITLE
bug in blog

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#389]
### Description

![image](https://user-images.githubusercontent.com/55352601/170180777-9ea937a6-d66f-4ee7-ace1-551c15724123.png)
![image](https://user-images.githubusercontent.com/55352601/170180794-0941f494-eb22-45ca-96f9-d4a12f78a15c.png)

**Comment by arpit456jain** [comment]
@muhammadgalhoum check it once

**Comment by muhammadgalhoum** [comment]
If the problem is still with you, assign this issue to me and I will push my code in a PR 
@arpit456jain

**Comment by arpit456jain** [comment]
I will try it once again and let you know

**Comment by arpit456jain** [comment]
@muhammadgalhoum

**Comment by muhammadgalhoum** [comment]
close this issue @arpit456jain
