### ISSUE TITLE
Would like to add html videos [OTHER] <description>

### ISSUE THREAD

**Issue by myhacktech** [arpit456jain/CodingEasy#390]
### What would you like to share?

i would complete  maximum topics of html in minimum videos

**Comment by arpit456jain** [comment]
@myhacktech since HMTL is way easier than any other course make sure to cover the topic as much as possible in video and add at least 4 videos in one PR for lvl2

**Comment by myhacktech** [comment]
> @myhacktech since HMTL is way easier than any other course make sure to cover the topic as much as possible in video and add at least 4 videos in one PR for lvl2

Sure!!!

**Comment by arpit456jain** [comment]
@myhacktech upload the videos on yt also and make sure to save the code in a text file for adding it in website

**Comment by myhacktech** [comment]
> @myhacktech upload the videos on yt also and make sure to save the code in a text file for adding it in website

ok sure sir

**Comment by arpit456jain** [comment]
@myhacktech  all done?

**Comment by myhacktech** [comment]
> @myhacktech all done?

yes sir ,uploaded upto last PR merged
