### ISSUE TITLE
Add online editor in C++ course and Bootstrap

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#391]
### Description

![image](https://user-images.githubusercontent.com/55352601/170182074-a139bb44-f774-4a6e-ac9d-dc3a2aa0d2ed.png)

**Comment by Jayanth-MKV** [comment]
assign @arpit456jain @KKhushhalR2405 @singhmansi25

**Comment by arpit456jain** [comment]
ok @Jayanth-MKV  make a PR for adding it in bootstrap
