### ISSUE TITLE
Responsiveness of other pages

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#4]

**Comment by arpit456jain** [comment]
@Atif0604 check other pages too and make them responsive. try to make separate PRs
try to make 1 common css file for main layout like for navbar and footer

**Comment by Atif0604** [comment]
Hey @arpit456jain there no issue with css but the problem is in the html files
I'll surely make all the pages responsive by making individuals PR for Individual pages

**Comment by arpit456jain** [comment]
Ok cool

**Comment by Atif0604** [comment]
Hey @arpit456jain you can close this now

**Comment by arpit456jain** [comment]
@Atif0604 make a new issue and try to make a css file which contain css which is common to whole website same css is written every course folder

**Comment by Atif0604** [comment]
Ok @arpit456jain I will a issue about this add a new common.css file in the root folder which common in all files

**Comment by Atif0604** [comment]
You can close this now
