### ISSUE TITLE
Add a documentation for virtual environment

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#53]

**Comment by tandrimasingha** [comment]
Full name: Tandrima Singha
GitHub Profile Link :https://github.com/tandrimasingha
Participant ID:1044
Approach for this Project: Adding documentation for virtual environment
Are you a participant in SWOC 2.0?
YES

**Comment by tandrimasingha** [comment]
Sir please can you tell me how to do the documentation.
I couldn't understand how to proceed.

**Comment by arpit456jain** [comment]
@Snehaa1203 can you please help her

**Comment by Snehaa1203** [comment]
Do we have to update the Readme?
Or its a separate section in project?

**Comment by arpit456jain** [comment]
in read me for project setup

**Comment by Snehaa1203** [comment]
https://docs.djangoproject.com/en/4.0/howto/windows/
Grab content from here, or you can go through some more documentation.
You can make changes in your cloned repo's readme.
Lmk if you get stuck somewhere. @tandrimasingha

**Comment by tandrimasingha** [comment]
How to do the stuffs can you please help me out. @Snehaa1203

**Comment by tandrimasingha** [comment]
Do I need to make a webpage on virtual environment @Snehaa1203

**Comment by Snehaa1203** [comment]
No, just update the readme.

**Comment by tandrimasingha** [comment]
So in the readme of Coding Easy, I have to add how to create a virtual environment

**Comment by Snehaa1203** [comment]
Fork this repo, clone your forked version.
In your local setup, add a separate section in readme as "PROJECT SETUP"
add the content for setting up the virtual environment there.
push the changes.
make a PR
then we'll review and merge it.
Is it fine @arpit456jain ?

**Comment by arpit456jain** [comment]
Yes
