### ISSUE TITLE
Restructure folder structure for django migration

### ISSUE THREAD

**Issue by Atif0604** [arpit456jain/CodingEasy#63]
Hey @arpit456jain Please assign

**Comment by arpit456jain** [comment]
@Atif0604 what do you want to do in this issue

**Comment by arpit456jain** [comment]
@7saikat7 please have a look on this issue and the issue for migration

**Comment by Atif0604** [comment]
I will make diff folder according to Django Structure

**Comment by arpit456jain** [comment]
@Atif0604 contact to @7saikat7 in the channel he will guide you

**Comment by Atif0604** [comment]
Sure
