### ISSUE TITLE
Add Dark mode

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#7]

**Comment by vaibhav-305** [comment]
hi, i would like to work on this issue, can u assign me this ?

**Comment by arpit456jain** [comment]
Go ahead

**Comment by arpit456jain** [comment]
Make a separate css file for dark mode

**Comment by vaibhav-305** [comment]
Should i also change image(put a related dark version of image) for dark mode in course-cards ?

**Comment by arpit456jain** [comment]
no that's not needed

**Comment by arpit456jain** [comment]
@vaibhav-305 any update

**Comment by vaibhav-305** [comment]
yes, working on it , almost done , i've chosen a dark blue theme for dark mode

**Comment by arpit456jain** [comment]
@vaibhav-305 make PR ASAP because we are going to **migrate it into Django soon.**  send it whatever u have done.
further work be done another PR its a very big work don't do it in one PR.

**Comment by arpit456jain** [comment]
@vaibhav-305 the project is migrated to Django but you didn't make the PR
