### ISSUE TITLE
Make a mentor section just below the project admin section and add the mentors

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#81]
these are the mentors add their name, pics and url of GitHub profile just like the Project admin section

@ankitapuri @7saikat7 @Snehaa1203

**Comment by Snehaa1203** [comment]
in the readme ?

**Comment by arpit456jain** [comment]
> in the readme ?

yes @Snehaa1203  

don't worry its not for u its for contributors , I mention the user id so that its easy for them to find mentors profile

**Comment by Atif0604** [comment]
I can work on this

**Comment by arpit456jain** [comment]
ok do it asap @Atif0604  and the migration also

**Comment by Atif0604** [comment]
> ok do it asap @Atif0604 and the migration also

Yup I'm up on the migration
