### ISSUE TITLE
Add django project structure and apps 

### ISSUE THREAD

**Issue by 7saikat7** [arpit456jain/CodingEasy#83]
Currently, we are done with the front end as of now and build a proper backend structure with apps 
Coding easy ---->auth
                    |----->courses
                    |------>home
                    
like this , you don't have to run the whole project just create a proper structure and make a route for homepage only .

**Comment by arpit456jain** [comment]
@Snehaa1203  @7saikat7 please look into this issue

**Comment by Snehaa1203** [comment]
Who is working on this?

**Comment by arpit456jain** [comment]
@Snehaa1203  currently no one but this is a urgent issue so if no contributor is taking this up , you  and @7saikat7 can make a basic structure...


one more thing @7saikat7 please create some more simple issue regarding backend

**Comment by Snehaa1203** [comment]
Okay, will see to it.

**Comment by Atif0604** [comment]
assign me

**Comment by arpit456jain** [comment]
@Atif0604 make  a new PR for this
