### ISSUE TITLE
make a contact us page implement contact us section in backend

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#90]

**Comment by Atif0604** [comment]
we just have to make contact us page and add the page to existing Django app ,right??

**Comment by arpit456jain** [comment]
yes but have to implement the backend also but you can done that in another PR first just make contact us page and link it in Django app must discuss with @7saikat7

**Comment by Atif0604** [comment]
sure 
will do that

**Comment by prateekmohanty63** [comment]
Hello
If this issue if still not resolved 
I am interested on working of this

**Comment by arpit456jain** [comment]
> Hello If this issue if still not resolved I am interested on working of this

@prateekmohanty63 there is a bug in the contact us features i am creating a new issue for that comment on that i will assign you
