### ISSUE TITLE
implement a download csv feature in admin panel for downloading the data as csv file

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#91]

**Comment by 7saikat7** [comment]
You can try with the Django import export which let you download in various file extension.

**Comment by harikishantk** [comment]
I would like to work on it. Have quite work experience in Django. Could you assign me up @arpit456jain ..

**Comment by harikishantk** [comment]
Hey there, 
There isn't any models created inside the [Dashboard/models.py](https://github.com/arpit456jain/CodingEasy/blob/master/DashBoard/models.py). I had installed necessary installation as per mentor @7saikat7  said above and froze it into `requirements.txt` file. If I merged PR, then only `requirements.txt` would be added.

**Comment by harikishantk** [comment]
# 1. Create Model 
![image](https://user-images.githubusercontent.com/58771359/151171678-a52c74a5-cecf-4912-b44d-6af80677bcc1.png)
# 2. Register the app in the admin.py 
![image](https://user-images.githubusercontent.com/58771359/151171780-8d90aa96-08ac-4c57-8f53-6cfe0f5321de.png)
# 3. Create data and save
![image](https://user-images.githubusercontent.com/58771359/151172092-30271fb3-9ed1-4ad6-9168-fd5aa7e3358a.png)
# 4. Click on export
![image](https://user-images.githubusercontent.com/58771359/151172293-85dac9b3-982c-464a-9508-2c1933f9160e.png)
# 5. Export it out as csv
![image](https://user-images.githubusercontent.com/58771359/151172408-e0801a9b-cff3-45b7-90a3-49fa660b7ba9.png)
[Author-2022-01-26.csv](https://github.com/arpit456jain/CodingEasy/files/7942085/Author-2022-01-26.csv)

**Comment by arpit456jain** [comment]
@7saikat7 please check his PR
