### ISSUE TITLE
Add Some Colors To C++ Content Page

### ISSUE THREAD

**Issue by Snehaa1203** [arpit456jain/CodingEasy#92]

**Comment by devesh-2002** [comment]
May I take up the issue?

**Comment by Snehaa1203** [comment]
Go ahead

**Comment by devesh-2002** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/79015420/148581355-2e62b89e-5374-461a-a5d5-baef3134febd.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/79015420/148581367-589e150f-a253-4e00-82ea-8b869854667a.png">
Should I add any more changes in this?

**Comment by arpit456jain** [comment]
@Snehaa1203 @ankitapuri

**Comment by Snehaa1203** [comment]
Looks better, what about some fonts too?

**Comment by Snehaa1203** [comment]
also, the background color is looking a bit less attractive, could you try something else?
@devesh-2002

**Comment by devesh-2002** [comment]
Should I add a darker background with white font?

**Comment by devesh-2002** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/79015420/148634772-d5f8ddd5-c8ae-49f8-898f-bc38e36770b0.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/79015420/148634773-877cb1b7-2c6e-42be-9e58-37b4a57e7310.png">
Is this better?

**Comment by Snehaa1203** [comment]
Previous one was better than this!!

**Comment by devesh-2002** [comment]
What should I do now?

**Comment by Snehaa1203** [comment]
Make it thr previous one and make a PR,I will merge the pr,
