### ISSUE TITLE
integrate  YouTube player in all courses

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#93]

**Comment by prateekmohanty63** [comment]
Hello I am interested in taking up this issue
Please tell me what needs to be done
And assign me this
Thank you

**Comment by prateekmohanty63** [comment]
Please assign under SWOC

**Comment by arpit456jain** [comment]
Go ahead @prateekmohanty63

**Comment by prateekmohanty63** [comment]
Can you please tell me what is the requirement exactly

**Comment by prateekmohanty63** [comment]
Like I have to integrate youtube link for the courses?

**Comment by prateekmohanty63** [comment]
@arpit456jain can you please explain m doubt

**Comment by arpit456jain** [comment]
@prateekmohanty63  i want a UI like this
https://codewithharry.com/videos/data-structures-and-algorithms-in-hindi-1/

in which we can links our videos from youtube

**Comment by prateekmohanty63** [comment]
@arpit456jain i have made the page
where all the course videos can come in a single page

**Comment by prateekmohanty63** [comment]
should i sent a pr to the master branch 
or my branch ?

**Comment by arpit456jain** [comment]
Master @prateekmohanty63

**Comment by prateekmohanty63** [comment]
sure
