### ISSUE TITLE
integrate editors to run the code dynamically like w3school and codepen

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#94]

**Comment by Vaishnavi1411** [comment]
Hii @arpit456jain I wish to work on this as a GSSOC 22 participant.
Can you please assign this to me!!

**Comment by arpit456jain** [comment]
go ahead @Vaishnavi1411

**Comment by Vaishnavi1411** [comment]
![editor-tour](https://user-images.githubusercontent.com/71778469/156629466-223e2a7e-c77d-4114-8701-c35401661cab.png)
Hii @arpit456jain !!
How does it looks, Can I create an editor like this using HTML, CSS, and JS...

**Comment by HarshKumarChoudary** [comment]
Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant

**Comment by HarshKumarChoudary** [comment]
@Vaishnavi1411 I guess you need to create a dynamic editor which displays the results. This could be done using APIs, just using HTML and CSS won't work.

**Comment by arpit456jain** [comment]
> @Vaishnavi1411 I guess you need to create a dynamic editor which displays the results. This could be done using APIs, just using HTML and CSS won't work.

@Vaishnavi1411 he is right are u able to do it?

**Comment by Vaishnavi1411** [comment]
Yes sir I know about API.I am able to do it.

**Comment by arpit456jain** [comment]
ok @Vaishnavi1411 go ahead

**Comment by arpit456jain** [comment]
@Vaishnavi1411 updates ?

**Comment by singhmansi25** [comment]
@Vaishnavi1411 
please update about your status of work.
Or else we will assign people waiting in queue to complete this issue.

**Comment by arpit456jain** [comment]
@HarshKumarChoudary r u interested ?

**Comment by HarshKumarChoudary** [comment]
yes I could work on it.

**Comment by Vaishnavi1411** [comment]
@arpit456jain I am working on it and I have shown the output to @singhmansi25  on discord!

**Comment by singhmansi25** [comment]
@arpit456jain 
Please let @Vaishnavi1411 to complete this by this week.
If she couldn't then may be we can assign to others.
**@Vaishnavi1411 
Please share your status of work here.**

**Comment by Vaishnavi1411** [comment]
ok @singhmansi25

**Comment by Vaishnavi1411** [comment]
![ss](https://user-images.githubusercontent.com/71778469/160225449-7a986857-602e-402c-92d0-664d9a9712a8.png)

**Comment by Vaishnavi1411** [comment]
![editor](https://user-images.githubusercontent.com/71778469/160225480-32f78aa2-79d5-45c0-89e7-45c8bcbc9668.png)

**Comment by arpit456jain** [comment]
Ok @Vaishnavi1411 make PR asap..

@HarshKumarChoudary wait for 1-2 days 
After that you can work on this issue or improve the work done by her

**Comment by Vaishnavi1411** [comment]
Ok @arpit456jain

**Comment by Vaishnavi1411** [comment]
Please review my PR.

**Comment by singhmansi25** [comment]
@Vaishnavi1411 
Reviewed.
@arpit456jain 
Please check the PR once.

**Comment by arpit456jain** [comment]
@Vaishnavi1411  make PR asap

**Comment by arpit456jain** [comment]
@singhmansi25 contact to her if she is unable to make PR and doesn't respond in 2 days assign this issue to @HarshKumarChoudary

**Comment by Vaishnavi1411** [comment]
Review my PR @arpit456jain
